### 1-Shot
../../anaconda3/bin/python3.7 train_fsl.py  --num_eval_episodes 600 --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --backbone_class ConvNet --dataset MiniImageNet --lr 0.001 --lr_scheduler step --step_size 10 --gamma 0.1 --augment --gpu 0 --orig_imsize -1 --balance 0.1 --kd_temperature 1 --temperature 0.5  --num_classes 5 --num_tasks 1 --repo_size 20  --num_workers 4 --eval_interval 2 --use_repo 1 --init_weights ../Castle/saves/initialization/miniimagenet/con-pre.pth --max_epoch 100 --kd_type NN  >> a1.txt
../../anaconda3/bin/python3.7 train_fsl.py  --num_eval_episodes 600 --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --backbone_class ConvNet --dataset MiniImageNet --lr 0.001 --lr_scheduler step --step_size 10 --gamma 0.5 --augment --gpu 0 --orig_imsize -1 --balance 0.1 --kd_temperature 1 --temperature 0.5  --num_classes 5 --num_tasks 1 --repo_size 20  --num_workers 4 --eval_interval 2 --use_repo 1 --init_weights ../Castle/saves/initialization/miniimagenet/con-pre.pth --max_epoch 100 --kd_type NN  >> a2.txt
../../anaconda3/bin/python3.7 train_fsl.py  --num_eval_episodes 600 --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --backbone_class ConvNet --dataset MiniImageNet --lr 0.001 --lr_scheduler step --step_size 20 --gamma 0.1 --augment --gpu 0 --orig_imsize -1 --balance 0.1 --kd_temperature 1 --temperature 0.5  --num_classes 5 --num_tasks 1 --repo_size 20  --num_workers 4 --eval_interval 2 --use_repo 1 --init_weights ../Castle/saves/initialization/miniimagenet/con-pre.pth --max_epoch 100 --kd_type NN  >> a3.txt
../../anaconda3/bin/python3.7 train_fsl.py  --num_eval_episodes 600 --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --backbone_class ConvNet --dataset MiniImageNet --lr 0.001 --lr_scheduler step --step_size 20 --gamma 0.5 --augment --gpu 0 --orig_imsize -1 --balance 0.1 --kd_temperature 1 --temperature 0.5  --num_classes 5 --num_tasks 1 --repo_size 20  --num_workers 4 --eval_interval 2 --use_repo 1 --init_weights ../Castle/saves/initialization/miniimagenet/con-pre.pth --max_epoch 120 --kd_type NN  >> a4.txt
../../anaconda3/bin/python3.7 train_fsl.py  --num_eval_episodes 600 --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --backbone_class ConvNet --dataset MiniImageNet --lr 0.001 --lr_scheduler step --step_size 10 --gamma 0.1 --augment --gpu 0 --orig_imsize -1 --balance 0.1 --kd_temperature 4 --temperature 0.5  --num_classes 5 --num_tasks 1 --repo_size 20  --num_workers 4 --eval_interval 2 --use_repo 1 --init_weights ../Castle/saves/initialization/miniimagenet/con-pre.pth --max_epoch 100 --kd_type NN  >> a5.txt
../../anaconda3/bin/python3.7 train_fsl.py  --num_eval_episodes 600 --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --backbone_class ConvNet --dataset MiniImageNet --lr 0.001 --lr_scheduler step --step_size 10 --gamma 0.5 --augment --gpu 0 --orig_imsize -1 --balance 0.1 --kd_temperature 4 --temperature 0.5  --num_classes 5 --num_tasks 1 --repo_size 20  --num_workers 4 --eval_interval 2 --use_repo 1 --init_weights ../Castle/saves/initialization/miniimagenet/con-pre.pth --max_epoch 100 --kd_type NN  >> a6.txt
../../anaconda3/bin/python3.7 train_fsl.py  --num_eval_episodes 600 --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --backbone_class ConvNet --dataset MiniImageNet --lr 0.001 --lr_scheduler step --step_size 20 --gamma 0.1 --augment --gpu 0 --orig_imsize -1 --balance 0.1 --kd_temperature 4 --temperature 0.5  --num_classes 5 --num_tasks 1 --repo_size 20  --num_workers 4 --eval_interval 2 --use_repo 1 --init_weights ../Castle/saves/initialization/miniimagenet/con-pre.pth --max_epoch 100 --kd_type NN  >> a7.txt
../../anaconda3/bin/python3.7 train_fsl.py  --num_eval_episodes 600 --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --backbone_class ConvNet --dataset MiniImageNet --lr 0.001 --lr_scheduler step --step_size 20 --gamma 0.5 --augment --gpu 0 --orig_imsize -1 --balance 0.1 --kd_temperature 4 --temperature 0.5  --num_classes 5 --num_tasks 1 --repo_size 20  --num_workers 4 --eval_interval 2 --use_repo 1 --init_weights ../Castle/saves/initialization/miniimagenet/con-pre.pth --max_epoch 120 --kd_type NN  >> a8.txt
../../anaconda3/bin/python3.7 train_fsl.py  --num_eval_episodes 600 --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --backbone_class ConvNet --dataset MiniImageNet --lr 0.001 --lr_scheduler step --step_size 10 --gamma 0.1 --augment --gpu 0 --orig_imsize -1 --balance 0.1 --kd_temperature 16 --temperature 0.5  --num_classes 5 --num_tasks 1 --repo_size 20  --num_workers 4 --eval_interval 2 --use_repo 1 --init_weights ../Castle/saves/initialization/miniimagenet/con-pre.pth --max_epoch 100 --kd_type NN  >> a9.txt
../../anaconda3/bin/python3.7 train_fsl.py  --num_eval_episodes 600 --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --backbone_class ConvNet --dataset MiniImageNet --lr 0.001 --lr_scheduler step --step_size 10 --gamma 0.5 --augment --gpu 0 --orig_imsize -1 --balance 0.1 --kd_temperature 16 --temperature 0.5  --num_classes 5 --num_tasks 1 --repo_size 20  --num_workers 4 --eval_interval 2 --use_repo 1 --init_weights ../Castle/saves/initialization/miniimagenet/con-pre.pth --max_epoch 100 --kd_type NN  >> a10.txt
../../anaconda3/bin/python3.7 train_fsl.py  --num_eval_episodes 600 --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --backbone_class ConvNet --dataset MiniImageNet --lr 0.001 --lr_scheduler step --step_size 20 --gamma 0.1 --augment --gpu 0 --orig_imsize -1 --balance 0.1 --kd_temperature 16 --temperature 0.5  --num_classes 5 --num_tasks 1 --repo_size 20  --num_workers 4 --eval_interval 2 --use_repo 1 --init_weights ../Castle/saves/initialization/miniimagenet/con-pre.pth --max_epoch 100 --kd_type NN  >> a11.txt
../../anaconda3/bin/python3.7 train_fsl.py  --num_eval_episodes 600 --way 5 --eval_way 5 --shot 1 --eval_shot 1 --query 15 --eval_query 15 --backbone_class ConvNet --dataset MiniImageNet --lr 0.001 --lr_scheduler step --step_size 20 --gamma 0.5 --augment --gpu 0 --orig_imsize -1 --balance 0.1 --kd_temperature 16 --temperature 0.5  --num_classes 5 --num_tasks 1 --repo_size 20  --num_workers 4 --eval_interval 2 --use_repo 1 --init_weights ../Castle/saves/initialization/miniimagenet/con-pre.pth --max_epoch 120 --kd_type NN  >> a12.txt